package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Quinta-feira, 21 de Abril de 2016 19h20min51s GFT
*/

public interface HelloOperations 
{
  String sayHello ();
  String listarContatos ();
  String adicionarContato (String contato);
  String removerContato (String contato);
  String buscarContato (String cpf);
  String editarContato (String cpf, String contato);
  void shutdown ();
} // interface HelloOperations
